name: figma_theme_generator
description: Generate themes from Figma styles.
version: 0.1.8
homepage: https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  figma_theme: ^0.1.1
  recase: ^4.0.0
  analyzer: any
  code_builder: ^4.1.0
  build: ^2.1.1
  source_gen: ^1.1.1
  meta: ^1.7.0
  dart_style: ^2.2.0
  figma: ^3.1.0

  flutter:
    sdk: flutter
